service: fib-generator
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: 20201221

functions:
  generate:
    handler: handler.generate
    events:
      - http:
          path: generate/{number}
          method: get
