service: fib-generator
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: 20201221

functions:
  generate:
    handler: handler.generate
    reservedConcurrency: 1
    events:
      - http:
          path: generate/{number}
          method: get

  dispatchLogs:
    handler: dispatch.handler
    environment: 
      logzio_token: wdSkRRNnIqqoncrvqfnGtwCKAUFEGPJd
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - "ses:*"        
        Resource: "*"

plugins:
  - serverless-iam-roles-per-function